import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by hediem",
};

const products = () => {
  return <div>products</div>;
};

export default products;
