import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Categories",
  description: "Generated by hediem",
};

const categories = () => {
  return <div>categories</div>;
};

export default categories;
