import React from "react";
import { cookies } from "next/headers";
import "@/styles/globals.scss";
import "@/public/assets/kits/colors/colors.css";
import "bootstrap/dist/css/bootstrap.css";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { AdminPanelContextProvider } from "@/context/AdminPanelContext";
import Encryption from "@/utils/generateToken";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by hediem",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("token")?.value;
  let userInfo;
  if (token !== undefined) {
    const data = Encryption.checkToken(token);
    if (data !== false) {
      userInfo = await fetch(`http://localhost:8000/users/${data}`, {
        method: "GET",
      }).then((res) => res.json());
    }
  }

  return (
    <html lang="en">
      <body className="Segoe UI Regular">
        <AdminPanelContextProvider previousInfo={userInfo}>
          {children}
        </AdminPanelContextProvider>
      </body>
    </html>
  );
}
