type StyleType = {
  white_0: string;
  blue1: string;
  blue2: string;
  background: string;
  type_primary: string;
  type_secondary: string;
  type_disabled: string;
  body_divider: string;
  input_border: string;
  input_hover_border: string;
  theme_primary: string;
  theme_background_light: string;
  theme_lighter_alt: string;
  theme_lighter: string;
  theme_light: string;
  theme_tertiary: string;
  theme_dark_alt: string;
  theme_dark: string;
  theme_darker: string;
  error_background_fill: string;
  success_background_fill: string;
  severe_warning_background_fill: string;
  warning_background_fill: string;
  status_error_type_icon: string;
  status_colors_error: string;
  status_success_type_icon: string;
  status_severe_warning_type_icon: string;
  status_warning_type_icon: string;
  overlay_light: string;
  overlay_dark: string;
  grey10: string;
  grey20: string;
  grey30: string;
  grey40: string;
  grey50: string;
  grey60: string;
  grey90: string;
  grey130: string;
  grey150: string;
  grey160: string;
  grey190: string;
};

const ColorSchema: StyleType = {
  white_0: "var(--white-0)",
  blue1: "var(--blue1)",
  blue2: "var(--blue2)",
  background: "var(--background)",
  type_primary: "var(--type-primary)",
  type_secondary: "var(--type-secondary)",
  type_disabled: "var(--type-disabled)",
  body_divider: "var(--body-divider)",
  input_border: "var(--input-border)",
  input_hover_border: "var(--input-hover-border)",
  theme_primary: "var(--theme-primary)",
  theme_background_light: "var(--theme-background-light)",
  theme_lighter_alt: "var(--theme-lighter-alt)",
  theme_lighter: "var(--theme-lighter)",
  theme_light: "var(--theme-light)",
  theme_tertiary: "var(--theme-tertiary)",
  theme_dark_alt: "var(--theme-dark-alt)",
  theme_dark: "var(--theme-dark)",
  theme_darker: "var(--theme-darker)",
  error_background_fill: "var(--error-background-fill)",
  success_background_fill: "var(--success-background-fill)",
  severe_warning_background_fill: "var(--severe-warning-background-fill)",
  warning_background_fill: "var(--warning-background-fill)",
  status_error_type_icon: "var(--status-error-type-icon)",
  status_colors_error: "var(--status-colors-error)",
  status_success_type_icon: "var(--status-success-type-icon)",
  status_severe_warning_type_icon: "var(--status-severe-warning-type-icon)",
  status_warning_type_icon: "var(--status-warning-type-icon)",
  overlay_light: "var(--overlay-light)",
  overlay_dark: "var(--overlay-dark)",
  grey10: "var(--grey10)",
  grey20: "var(--grey20)",
  grey30: "var(--grey30)",
  grey40: "var(--grey40)",
  grey50: "var(--grey50)",
  grey60: "var(--grey60)",
  grey90: "var(--grey90)",
  grey130: "var(--grey130)",
  grey150: "var(--grey150)",
  grey160: "var(--grey160)",
  grey190: "var(--grey190)",
};

export default ColorSchema;
