import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Analysis",
  description: "Generated by hediem",
};

const analysis = () => {
  return <div>analysis</div>;
};

export default analysis;
